"""Ports (interfaces) for external dependencies, defined in domain layer."""

from collections.abc import Sequence
from typing import Any, Protocol


class SemanticSolverPort(Protocol):
    def validate(self, context: Any, constraints: Sequence[Any]) -> Any: ...


class TemplateRendererPort(Protocol):
    def render(self, template_path: str, context: dict[str, Any]) -> str: ...
    def render_from_string(self, template_str: str, context: dict[str, Any]) -> str: ...


class AstPatchPort(Protocol):
    def parse(self, source: str) -> Any: ...
    def unparse(self, tree: Any) -> str: ...
    def apply_operation(self, tree: Any, operation: Any, target_selector: Any = None) -> Any: ...


class SemanticExtractorPort(Protocol):
    def extract_from_entry(self, entry: Any) -> list: ...


class KnowledgeGraphPort(Protocol):
    def outgoing_relations(self, instance_id: str) -> list: ...
    def incoming_relations(self, instance_id: str) -> list: ...
    def reachable(self, start_id: str, **kw) -> list[str]: ...


class DiagnosticsPort(Protocol):
    def add_error(self, msg: str) -> None: ...
    def add_warning(self, msg: str) -> None: ...
    @property
    def has_errors(self) -> bool: ...
